apiVersion: argoproj.io/valpha1
kind: Application
metadata:
  name: carvilla
  namespace: argocd
spec: 
  project: default

  source:
    repoURL: https://github.com/lightsspeed/argocdcheck.git
    targetRevision: HEAD
    path: 
  destination:
    server: https://kubernetes.default.svc
    namespace: mycarvilla

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true